# Generated by Django 4.2.3 on 2024-06-26 01:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('owner', models.TextField(blank=True, null=True, verbose_name='Создатель')),
                ('priority', models.CharField(blank=True, choices=[('Легкий', 'Легкий'), ('Обычный', 'Обычный'), ('Сложный', 'Сложный')], default='Обычный', max_length=50, verbose_name='Приоритет')),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 26, 1, 8, 25, 561735), null=True, verbose_name='Дата создания')),
                ('date_of_staging', models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 26, 1, 8, 25, 561768), null=True, verbose_name='Дата сдачи')),
                ('is_archive', models.CharField(blank=True, default='0', max_length=5, verbose_name='Статус архива')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, max_length=100, null=True, verbose_name='Токен')),
                ('war_token', models.TextField(blank=True, max_length=100, null=True, verbose_name='Боевой токен')),
                ('telegram_id', models.TextField(blank=True, max_length=100, null=True, verbose_name='Telegram ID')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_user', to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='Комментарий')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер задачи')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
